# See the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  - package-ecosystem: npm
    directory: /cdk # Location of package.json
    schedule:
      interval: weekly
    groups:
      npm-development: { dependency-type: development }
      npm-production: { dependency-type: production }
  - package-ecosystem: bundler
    directory: /web # Location of Gemfile
    schedule:
      interval: weekly
    groups:
      bundler-development: { dependency-type: development }
      bundler-production: { dependency-type: production }
  - package-ecosystem: github-actions
    directory: / # Required for GitHub Actions, see https://docs.github.com/en/code-security/dependabot/working-with-dependabot/dependabot-options-reference#directories-or-directory--
    schedule:
      interval: weekly
    groups:
      github-actions-development: { dependency-type: development }
      github-actions-production: { dependency-type: production }
  - package-ecosystem: devcontainers
    directory: / # Required for Dev container features, see https://containers.dev/guide/dependabot
    schedule:
      interval: weekly
    groups:
      devcontainers-development: { dependency-type: development }
      devcontainers-production: { dependency-type: production }
